version: '3.0'
services:
    odoo:
        container_name: odoo_farmacias_server
        image: odoo:17.0
        volumes:
            - odoo-web-data:/var/lib/odoo
            - ./conf:/etc/odoo
            - ./addons-extra:/mnt/extra-addons
        ports:
            - "9069:9069"
        depends_on:
            - postgres
    postgres:
        image: postgres:16
        container_name: postgres_odoo
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - odoo-db-data:/var/lib/postgresql/data/pgdata
    nginx:
        container_name: nginx_odoo
        image: nginx:latest
        restart: unless-stopped
        ports:
            - 8080:80
            - 443:443
        volumes:
            - ./nginx/conf:/etc/nginx/conf.d
            - ./certbot/conf:/etc/nginx/ssl
            - ./certbot/data:/var/www/html
    certbot:
        container_name: certbot_odoo
        image: certbot/certbot:latest
        command: certonly --webroot --webroot-path=/var/www/html -- email youremail@mail.com --agree-tos --no-eff-email -d domain.com -d www.domain.com
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/logs:/var/log/letsencrypt
            - ./certbot/data:/var/www/html
volumes:
    odoo-web-data:
    odoo-db-data: