version: "3.9"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    restart: unless-stopped
    networks:
      - odoo-net

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: /bin/sh
    command: >
      -c "certbot certonly --webroot
      --webroot-path=/var/www/certbot
      --email lolo.bravo@inbrasol.pe
      --agree-tos
      --no-eff-email
      --keep-until-expiring
      --non-interactive
      -d lailengfarma.inbrasol.pe"
    depends_on:
      - nginx

  odoo_lailengfarma:
    build: .
    container_name: odoo_lailengfarma
    environment:
      HOST: db-postgresql-odoo-community-do-user-13261802-0.b.db.ondigitalocean.com
      PORT: 25060
      USER: odoo-farmacias
      PASSWORD: Demo
    volumes:
      - ./conf/lailengfarma.conf:/etc/odoo/odoo.conf:ro
      - lailengfarma_data:/var/lib/odoo
    restart: unless-stopped
    networks:
      - odoo-net

volumes:
  lailengfarma_data:

networks:
  odoo-net: